--- 
files: 
  - 
    destination: /home/ubuntu/hmp-ordering-api
    source: /
hooks: 
  AfterInstall: 
    - 
      location: scripts/build_code.sh
      runas: root
      timeout: 60
  ApplicationStart: 
    - 
      location: scripts/start_server.sh
      runas: root
      timeout: 30
  BeforeInstall: 
    - 
      location: scripts/stop_server.sh
      runas: root
      timeout: 30
os: linux
version: 0.0
